# Generated by Django 4.1.2 on 2022-11-29 14:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import studyarea.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=256)),
                ('display_first_name', models.CharField(max_length=32)),
                ('display_last_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StudyArea',
            fields=[
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=120)),
                ('features', models.JSONField(null=True)),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('study_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='studyarea.studyarea')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(default=studyarea.models.generate_id, primary_key=True, serialize=False, unique=True)),
                ('creator', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('study_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='studyarea.studyarea')),
            ],
        ),
    ]
