# Generated by Django 4.1.2 on 2022-10-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('room_id', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=120)),
                ('features', models.JSONField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
