# Generated by Django 4.1.2 on 2022-11-29 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyarea',
            name='room_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[a-zA-Z]-\\d\\d\\d')]),
        ),
    ]
