# Generated by Django 4.1.2 on 2022-10-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyarea', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=256)),
                ('display_first_name', models.CharField(max_length=32)),
                ('display_last_name', models.CharField(max_length=32)),
            ],
        ),
    ]
