# Generated by Django 4.1.3 on 2022-11-30 01:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studyarea', '0003_alter_studyarea_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyarea',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AC', 'Air Conditioner'), ('PC', 'Computers'), ('WB', 'Whiteboard'), ('NONE', 'None')], max_length=4),
        ),
    ]
