# Generated by Django 4.1.3 on 2022-11-30 02:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studyarea', '0005_alter_studyarea_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyarea',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Air Conditioner', 'Air Conditioner'), ('Computers', 'Computers'), ('Whiteboard', 'Whiteboard'), ('None', 'None')], max_length=300),
        ),
    ]
