# Generated by Django 4.1.3 on 2022-11-30 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyarea', '0008_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyarea',
            name='room_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[a-zA-Z]+-[0-9]+')]),
        ),
    ]
