# Generated by Django 4.1.3 on 2022-11-30 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyarea', '0010_alter_studyarea_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyarea',
            name='room_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z]+-[A-Za-z0-9]+')]),
        ),
    ]
